steps:
#- name: gcr.io/cloud-builders/gradle
#- name: gcr.io/cloud-builders/gcloud
#  entrypoint: bash
#  args:
#  - -c
#  - |
#    gcloud components install app-engine-java

- name: gcr.io/cloud-builders/gradle
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
  - -c
  - |
    ./gradlew appengineDeploy


#- name: gcr.io/cloud-builders/javac
#  entrypoint: bash
#  args:
#  - -c
#  - |
#    ./gradlew appengineDeploy
